version: 2.1
orbs:
  pulumi: pulumi/pulumi@1.2.0
  aws-s3: circleci/aws-s3@1.0.12
  aws-cli: circleci/aws-cli@0.1.19

executors:
  aws_cli:
    docker:
      - image: aws-cli/default
    working_directory: ~/topmonks-webs

commands:
  read_deployment_envs:
    parameters:
      site_name:
        type: string
    steps:
      - pulumi/login:
          cloud-url: s3://pulumi.tmcloud.io
      - run:
          command: |
            CLOUDFRONT_ID=$(pulumi stack output sites --stack topmonks-webs | jq -rM  '.["<< parameters.site_name >>"] | .cloudFrontId | @text')
            echo "export AWS_CLOUDFRONT_DISTRIBUTION_ID=\"${CLOUDFRONT_ID}\"" >> $BASH_ENV
  invalidate_cloudfront:
    parameters:
      distribution_id:
        type: string
      paths:
        type: string
    steps:
      - run:
          name: Invalidate Cloudfront distribution
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id=<< parameters.distribution_id >> --paths=<< parameters.paths >>
  deploy_website:
    parameters:
      site_name:
        type: string
      distribution_id:
        type: string
        default: "${AWS_CLOUDFRONT_DISTRIBUTION_ID}"
      paths:
        type: string
        default: "/*"
    steps:
      - aws-cli/install
      - read_deployment_envs:
          site_name: << parameters.site_name >>
      - aws-s3/sync:
          from: public/<< parameters.site_name >>
          to: s3://<< parameters.site_name >>
      - invalidate_cloudfront:
          distribution_id: << parameters.distribution_id >>
          paths: << parameters.paths >>

test-site: &test-site
  docker:
    - image: circleci/node:12-browsers
  working_directory: ~/topmonks-webs
  steps:
    - checkout
    - attach_workspace:
        at: ~/topmonks-webs
    - restore_cache:
        keys:
          - v5-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn install --frozen-lockfile --link-duplicates --no-progress
    - run:
        name: Install self-signed cert for localhost
        command: |
          sudo apt-get install libnss3-tools
          mkdir -p $HOME/.pki/nssdb
          certutil -d $HOME/.pki/nssdb -N --empty-password
          certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n lws-cert -i ./node_modules/lws/ssl/lws-cert.pem
    - run:
        name: Serve site content
        command: yarn serve
        background: true
    - run:
        name: Test site with Lighthouse
        command: |
          mkdir results
          yarn test:lighthouse
          yarn test:ava
    - run:
        name: Check site for broken links
        command: yarn test:broken-links:$HOST
    - store_artifacts:
        path: ./results
    - store_test_results:
        path: ./results

jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/topmonks-webs
    steps:
      - checkout
      - pulumi/login:
          cloud-url: s3://pulumi.tmcloud.io
      - restore_cache:
          keys:
            - v5-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile --link-duplicates --no-progress
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v5-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: |
          mkdir results
          yarn test
      - store_artifacts:
          path: ./results
      - store_test_results:
          path: ./results
      - persist_to_workspace:
          root: .
          paths: public

  provision:
    docker:
      - image: circleci/node:12
    working_directory: ~/topmonks-webs
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - pulumi/login:
          cloud-url: s3://pulumi.tmcloud.io
      - restore_cache:
          keys:
            - v5-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: yarn install --frozen-lockfile --production --no-progress --link-duplicates
      - pulumi/update:
          stack: topmonks-webs
          skip-preview: true

  preview-provision:
    docker:
      - image: circleci/node:12
    working_directory: ~/topmonks-webs
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - pulumi/login:
          cloud-url: s3://pulumi.tmcloud.io
      - restore_cache:
          keys:
            - v5-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: yarn install --frozen-lockfile --production --no-progress --link-duplicates
      - pulumi/preview:
          stack: topmonks-webs

  test-prodeti-topmonks-cz:
    <<: *test-site
    environment:
      HOST: prodeti.topmonks.cz

  deploy-prodeti-topmonks-cz:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: prodeti.topmonks.cz

  test-blockchain-topmonks-com:
    <<: *test-site
    environment:
      HOST: blockchain.topmonks.com

  deploy-blockchain-topmonks-com:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: blockchain.topmonks.com

  test-studio-topmonks-com:
    <<: *test-site
    environment:
      HOST: studio.topmonks.com

  deploy-monkstage-topmonks-com:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: monkstage.topmonks.com

  test-monkstage-topmonks-com:
    <<: *test-site
    environment:
      HOST: monkstage.topmonks.com

  deploy-session-monk-topmonks-com:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: session-monk.topmonks.com

  test-session-monk-topmonks-com:
    <<: *test-site
    environment:
      HOST: session-monk.topmonks.com

  deploy-studio-topmonks-com:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: studio.topmonks.com

  test-www-topmonks-com:
    <<: *test-site
    environment:
      HOST: www.topmonks.com

  deploy-www-topmonks-com:
    executor: aws-cli/default
    working_directory: ~/topmonks-webs
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: www.topmonks.com

  test-www-topmonks-cz:
    <<: *test-site
    environment:
      HOST: www.topmonks.cz

  deploy-www-topmonks-cz:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: www.topmonks.cz

  test-caffe-topmonks-cz:
    <<: *test-site
    environment:
      HOST: caffe.topmonks.cz

  deploy-caffe-topmonks-cz:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: caffe.topmonks.cz

  test-www-hookamonk-com:
    <<: *test-site
    environment:
      HOST: www.hookamonk.com

  deploy-www-hookamonk-com:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - aws-s3/sync:
          from: public/www.hookamonk.com
          to: s3://www.hookamonk.com
      - run:
          name: Update MIME types
          command: aws s3 cp --exclude "*" --include "apple-app-site-association" --content-type="application/json; charset=utf-8" --metadata-directive="REPLACE" --recursive s3://session-monk.topmonks.com/ s3://session-monk.topmonks.com/
      - invalidate_cloudfront:
          distribution_id: E2EF8JLZURG0RI
          paths: "/*"

  test-monkslab-cz:
    <<: *test-site
    environment:
      HOST: monkslab.cz

  deploy-monkslab-cz:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: monkslab.cz

  test-www-hlidacshopu-cz:
    <<: *test-site
    environment:
      HOST: www.hlidacshopu.cz

  deploy-www-hlidacshopu-cz:
    executor: aws_cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - deploy_website:
          site_name: www.hlidacshopu.cz

workflows:
  build_and_deploy:
    jobs:
      - build:
          context: org-global
      - preview-provision:
          context: org-global
          filters:
            branches:
              ignore: master
      - provision:
          context: org-global
          filters:
            branches:
              only: master
      - test-www-topmonks-com:
          requires:
            - build
      - test-blockchain-topmonks-com:
          requires:
            - build
      - test-studio-topmonks-com:
          requires:
            - build
      - test-monkstage-topmonks-com:
          requires:
            - build
      - test-www-topmonks-cz:
          requires:
            - build
      - test-caffe-topmonks-cz:
          requires:
            - build
      - test-prodeti-topmonks-cz:
          requires:
            - build
      - deploy-prodeti-topmonks-cz:
          context: org-global
          requires:
            - provision
            - test-prodeti-topmonks-cz
          filters:
            branches:
              only: master
      - test-session-monk-topmonks-com:
          requires:
            - build
      - deploy-session-monk-topmonks-com:
          context: org-global
          requires:
            - provision
            - test-session-monk-topmonks-com
          filters:
            branches:
              only: master
      - deploy-www-topmonks-com:
          context: org-global
          requires:
            - provision
            - test-www-topmonks-com
          filters:
            branches:
              only: master
      - deploy-www-topmonks-cz:
          context: org-global
          requires:
            - provision
            - test-www-topmonks-cz
          filters:
            branches:
              only: master
      - deploy-blockchain-topmonks-com:
          context: org-global
          requires:
            - provision
            - test-blockchain-topmonks-com
          filters:
            branches:
              only: master
      - deploy-monkstage-topmonks-com:
          context: org-global
          requires:
            - provision
            - test-monkstage-topmonks-com
          filters:
            branches:
              only: master
      - deploy-studio-topmonks-com:
          context: org-global
          requires:
            - provision
            - test-studio-topmonks-com
          filters:
            branches:
              only: master
      - deploy-caffe-topmonks-cz:
          context: org-global
          requires:
            - provision
            - test-caffe-topmonks-cz
          filters:
            branches:
              only: master
      - test-monkslab-cz:
          requires:
            - build
      - deploy-monkslab-cz:
          context: org-global
          requires:
            - provision
            - test-monkslab-cz
          filters:
            branches:
              only: master
      - deploy-www-hookamonk-com:
          context: org-global
          requires:
            - provision
            - build
          filters:
            branches:
              only: master
      - test-www-hlidacshopu-cz:
          requires:
            - build
      - deploy-www-hlidacshopu-cz:
          context: org-global
          requires:
            - provision
            - test-www-hlidacshopu-cz
          filters:
            branches:
              only: master
