version: '3.3'
services:
  lhserver:
    image: topmonks/lhci-server:latest
    environment:
      DB_NAME: lhci
      DB_SERVER: dev-postgres.cwd4mvussnuk.eu-central-1.rds.amazonaws.com:5432
      DB_PASSWORD_FILE: /run/secrets/postgres-password
      DB_USER: monkadmin
    networks:
      - proxy
    secrets:
      - postgres-password
    volumes:
      - lhci-data:/data
    deploy:
      replicas: 1
      labels:
        traefik.frontend.headers.STSSeconds: '315360000'
        traefik.frontend.headers.forceSTSHeader: 'true'
        traefik.frontend.headers.STSIncludeSubdomains: 'true'
        traefik.frontend.headers.STSPreload: 'true'
        traefik.docker.network: proxy
        traefik.enable: 'true'
        traefik.port: '9001'
        traefik.frontend.rule: Host:lhci.dev.tmcloud.io
      placement:
        constraints:
          - node.role == worker
secrets:
  postgres-password:
    external: true
networks:
  proxy:
    external: true
volumes:
  lhci-data:
    driver: cloudstor:aws
